In [6]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

In [7]:
info = make_array("Shelby", "Fletcher", "Florida", "Blue")

In [8]:
upper = np.char.upper(info)

In [9]:
upper

array(['SHELBY', 'FLETCHER', 'FLORIDA', 'BLUE'], dtype='<U8')

In [10]:
print(upper)

['SHELBY' 'FLETCHER' 'FLORIDA' 'BLUE']


In [11]:
anum = np.char.count(info, 'a')

In [12]:
anum

array([0, 0, 1, 0])

In [13]:
length = len(info)

In [14]:
length

4

In [26]:
odds = np.arange(1,43,4)

In [29]:
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [30]:
oddsums = np.sum(odds)

In [31]:
oddsums

231

In [38]:
floatodd = odds.astype(float)

In [39]:
oddproduct = np.prod(floatodd)

In [40]:
oddproduct

7579867420125.0

In [41]:
lnodd = np.log(floatodd)

In [42]:
lnodd

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

In [43]:
adjdiff = np.diff(odds)

In [44]:
sumofdiff = np.sum(adjdiff)

In [45]:
sumofdiff

40